### PR TITLE
Linux Support

### PR DESCRIPTION
**Pull request by mattnite**
This is a WIP patch to support Linux. I don't know what we're going to run into along the way for window management and other UI stuff like that, but I hope I can rope @marler8997 in to help deal with X.

### CODE REVIEW

**Comment by pldiiw** [comment]
I'm interested in working on a Linux port too. I've picked up your patch and
continued adding empty stubs where needed. It's now able to build the runtime
and bundle apps. Running an app will crash right away as all platform-specific
procedures have `assert(0)` as their body. You can find the patch here:

https://git.pld.tf/orca/diff?id=pld/linux&id2=main

Will put it on GitHub proper later.

I intend to continue from there. My next goal is to get an X11 window onto the
screen. @mattnite, following you sharing this in-progress patch, is there
anything in particular you were planning to work on in the coming weeks? Just
so that I'm aware and we don't end up stepping onto one another's feet too
much.

**Comment by squidink7** [comment]
Just a note before this gets too far along, both Gnome and KDE are moving to Wayland by default and Fedora is even outright removing xorg as an option. If it would be easier (and given how people talk about xorg development it likely is) then I'd perhaps suggest targeting Wayland at least at first, as that seems to be where desktop Linux is headed ([some apps](https://support.presonus.com/hc/en-us/articles/19214558269581-Linux-Getting-Started) are even going Wayland only)

**Comment by pldiiw** [comment]
Yeah, I 100% agree a Wayland client will be needed. I'm going for X11 first as it's what my laptop runs, and while Xorg is deprecated, the X11 protocol will remain indefinitely (through Xwayland). Once we have X11 in place and working, Wayland would be next. X11 also allows porting to BSDs, the switch to Wayland there seems even slower than in Linux-land.

AFAICT, what we'll be missing by going with X11 for the first few months are mostly things like Hi-DPI and fractional scaling for Wayland users. I'm learning, so I'm discovering the rough edges as I go.

It's also hard to find recent stats on the X11 vs Wayland market share. Last I could find date back from February 2022:

https://www.phoronix.com/news/Firefox-Wayland-X11-Stats

Most of the communication from distros saying "we're *finally* dropping Xorg" seems more recent than that, so I'm curious what the numbers are as of December 2023/January 2024.

I was hoping the Steam Hardware & Software survey would have this data point, but it doesn't.

**Comment by Conan-Kudo** [comment]
For what it's worth, the most popular desktops are on a path to offer only Wayland sessions in the next few months (Budgie) or years (GNOME and KDE). Several others are going to start offering Wayland environments (LXQt, Xfce, and Cinnamon). Additionally, *new* desktops are being created that are Wayland-only (COSMIC). New window manager environments are Wayland only (Sway, Miracle, labwc, and Wayfire) to replace their old (and sometimes unmaintained) X11 counterparts.

I would definitely suggest prioritizing Wayland if you can.

**Comment by mattnite** [comment]
Hey just doing some cleanup of my Github, unfortunately I don't have the time to drive something like this home. I wish the project luck! See you at handmade

**Pull request closed without merging**
